export const counties = [
  "Alba",
  "Arad",
  "Argeş",
  "Bacău",
  "Bihor",
  "Bistriţa - Năsăud",
  "Botoşani",
  "Braşov",
  "Brăila",
  "Buzău",
  "Caraş - Severin",
  "Călăraşi",
  "Cluj",
  "Constanţa",
  "Covasna",
  "Dâmboviţa",
  "Dolj",
  "Galaţi",
  "Giurgiu",
  "Gorj",
  "Harghita",
  "Hunedoara",
  "Ialomiţa",
  "Iaşi",
  "Ilfov",
  "Maramureş",
  "Mehedinţi",
  "Mureş",
  "Neamţ",
  "Olt",
  "Prahova",
  "Satu Mare",
  "Sălaj",
  "Sibiu",
  "Suceava",
  "Teleorman",
  "Timiş",
  "Tulcea",
  "Vaslui",
  "Vâlcea",
  "Vrancea",
  "Bucuresti",
];

export const categories = [
  {
    group: "Alimentatie",
    items: [
      "Restaurante",
      "Fast-food",
      "Cafenele",
      "Cofetarii/patiserii",
      "Gelaterii",
      "Pizzerii",
    ],
  },
  {
    group: "Magazine",
    items: [
      "Haine",
      "Incaltaminte",
      "Articole pt copii",
      "Produse cosmetice",
      "Plafar",
      "Papetarie",
      "Electronice",
      "Florarii",
      "Bacanie",
      "Librarii",
      "Suveniruri",
      "Magazin apicol",
    ],
  },
  {
    group: "Frumusețe & Îngrijire personală",
    items: [
      "Saloane de infrumusetare",
      "Frizerii",
      "Barbershop",
      "Saloane de manichiura",
      "Masaj & Spa",
      "Cosmetica",
      "Saloane de coafura",
    ],
  },

  {
    group: "Sanatate si fitness",
    items: [
      "Sali de fitness",
      "Cabinete stomatologice",
      "Cabinete medicale",
      "Cabinete oftalmologice",
      "Nutritie",
      "Yoga",
      "Kinetoterapie",
    ],
  },
  {
    group: "Evenimente",
    items: [
      "Organizatori de evenimente",
      "Locatii pentru evenimente",
      "Foto/video",
      "Tinute speciale",
      "Articole pentru nunta",
    ],
  },
  {
    group: "Auto & Transport",
    items: [
      "Spalatorii auto",
      "Service auto",
      "Vulcanizari",
      "Inchirieri auto",
      "Taxi/ride-sharing",
      "Curse",
    ],
  },
  {
    group: "Animale de companie",
    items: ["Pet shop", "Cabinete veterinare", "Frizerie canica", "Dresaj"],
  },
  {
    group: "Reparații & Meșteșuguri",
    items: [
      "Reparatii telefoane",
      "Croitorii",
      "Tamplarie",
      "Ceasornicarii",
      "Cizmarii",
    ],
  },
  {
    group: "Îngrijire & Curățenie",
    items: [
      "Curatare pantofi",
      "Spalatorii",
      "Curatatorii chimice",
      "Detailing auto",
      "Curatenie profesionala",
    ],
  },
  {
    group: "Educație & Activități",
    items: ["Cursuri", "Ateliere", "Scoli"],
  },
  {
    group: "Artă & Handmade",
    items: [
      "Bijuterii handmade",
      "Artizanat",
      "Pictura",
      "Produse personalizate",
    ],
  },
  {
    group: "Turism & Cazare",
    items: ["Pensiuni", "Ghizi locali", "Camping", "Tururi organizate"],
  },
  {
    group: "Servicii Digitale & Consultanță",
    items: [
      "Design grafic",
      "Social media",
      "Contabilitate",
      "Web development",
      "Traduceri",
    ],
  },
  {
    group: "Cultură & Experiențe",
    items: [
      "Muzee",
      "Teatre",
      "Galerii de arta",
      "Escape rooms",
      "Case memoriale",
      "Spectacole",
    ],
  },

  {
    group: "Distractie si recreere",
    items: ["Sala de jocuri video", "Bowling/biliard"],
  },
  {
    group: "Turism",
    items: ["Agentii de turism"],
  },
];
